[package]
name = "rdp-bruteforcer"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rdp-rs = "0.1.0"
socks = "0.3.4"
clap = { version = "4.0.29", features = ["derive"] }
